// packages/solid-00/src/App.tsx
import { createSignal, type Component, For, batch, Show } from "solid-js";

import styles from "./App.module.css";

import { create00Cache } from "./doublezero";

const App: Component = () => {
  const [title, set_title] = createSignal("");

  const stores = create00Cache("bub", {
    count: {
      initial_data: {
        count: 0,
      },
    },
    todos: {
      initial_data: {},
    },
  });

  return (
    <Show when={stores()}>
      <div class={styles.App}>
        <button
          onClick={() => stores()?.count.set_data((c) => ({ ...c, count: c.count + 1 }))}
        >
          +
        </button>
        <button
          onClick={() => stores()?.count.set_data((c) => ({ ...c, count: c.count - 1 }))}
        >
          -
        </button>
        <div>count: {stores()?.count.data().count}</div>

        <div>
          <input value={title()} onInput={(e) => set_title(e.target.value)} />
          <button
            onClick={() => {
              batch(() => {
                stores()?.todos.set_data((c) => {
                  const id = crypto.randomUUID();
                  return {
                    ...c,
                    [id]: {
                      id,
                      title: title(),
                      checked: false,
                    },
                  };
                });
                set_title("");
              });
            }}
          >
            add
          </button>
        </div>
        <ul>
          <For each={Object.entries(stores()?.todos.data())}>
            {([id, t]) => {
              return (
                <li>
                  {t.title}
                  <input
                    type="checkbox"
                    checked={t.checked}
                    onChange={(e) =>
                      stores()?.todos.set_data((c) => {
                        return {
                          ...c,
                          [id]: {
                            ...c[id],
                            checked: e.target.checked,
                          },
                        };
                      })
                    }
                  />
                  <button
                    onClick={() => {
                      stores()?.todos.set_data((c) => {
                        const curr = { ...c };
                        delete curr[id];

                        return curr;
                      });
                    }}
                  >
                    delete
                  </button>
                </li>
              );
            }}
          </For>
        </ul>
      </div>
    </Show>
  );
};

export default App;

// examples/react/src/App.tsx
import { useState } from "react";
import { observer } from "mobx-react";

import { create00Cache } from "@doublezero/mobx";

const stores = await create00Cache("bub", {
  todos: {
    initial_data: {},
  },
  count: {
    initial_data: {
      count: 0,
    },
  },
});

function TodoInput() {
  const [title, setTitle] = useState("");

  return (
    <div>
      <input value={title} onChange={(e) => setTitle(e.target.value)} />
      <button
        onClick={() => {
          setTitle("");
          stores.todos.mutate((c) => {
            const id = crypto.randomUUID();
            return {
              ...c,
              [id]: {
                id,
                title,
                checked: false,
              },
            };
          });
        }}
      >
        Add
      </button>
    </div>
  );
}

const TodoList = observer(() => {
  return (
    <ul>
      {Object.entries(stores.todos.data).map(([id, todo]) => {
        return (
          <li key={id}>
            {todo.title}
            <input
              type="checkbox"
              checked={todo.checked}
              onChange={() =>
                stores.todos.mutate((c) => {
                  return {
                    ...c,
                    [id]: {
                      ...c[id],
                      checked: !c[id].checked,
                    },
                  };
                })
              }
            />
            <button
              onClick={() =>
                stores.todos.mutate((c) => {
                  const todos = { ...c };
                  delete todos[id];
                  return todos;
                })
              }
            >
              delete
            </button>
          </li>
        );
      })}
    </ul>
  );
});

const Count = observer(() => {
  return (
    <div>
      <button onClick={() => stores.count.mutate((c) => ({ ...c, count: c.count + 1 }))}>
        Increment
      </button>
      <button onClick={() => stores.count.mutate((c) => ({ ...c, count: c.count - 1 }))}>
        Decrement
      </button>
      <button onClick={() => stores.count.mutate((c) => ({ ...c, count: c.count * 2 }))}>
        Double
      </button>
      {stores.count.data.count}
    </div>
  );
});

function App() {
  return (
    <>
      <TodoInput />
      <TodoList />
      <Count />
    </>
  );
}

export default App;
